#_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "sam_vit_h_4b8939.pth"
INPUT:
  FORMAT: "RGB"
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
  WEIGHT_DECAY: 0.05
  BASE_LR: 0.0001
  AMP:
    ENABLED: True
TEST:
  EVAL_PERIOD: 20000 

DATASETS:
  TRAIN: ("experiment",)
  TEST: ("experiment_test",)

OUTPUT_DIR: ./output
SEED: -1


