_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  #WEIGHTS: "/home/fariborz_taherkhani/SwinT_detectron2-main_sam/sam_vit_h_4b8939.pth"
  # PIXEL_MEAN: [123.675, 116.28, 103.53]
  # PIXEL_STD: [58.395, 57.12, 57.375]
  MASK_ON: True
  # RESNETS:
    # DEPTH: 50
  BACKBONE:
    NAME: "build_swint_fpn_backbone"
  # SWINT:
    # OUT_FEATURES: ["stage2", "stage3", "stage4", "stage5"]
  FPN:
    IN_FEATURES: ["stage1", "stage2", "stage3", "stage4"]
INPUT:
  FORMAT: "RGB"
SOLVER:
  STEPS: (420000, 500000)
  MAX_ITER: 800000
  WEIGHT_DECAY: 0.000005
  BASE_LR: 0.0001
  AMP:
    ENABLED: True
TEST:
  EVAL_PERIOD: 20000 

DATASETS:
  TRAIN: ("experiment",)
  TEST: ("experiment_test",)
